// Source for the stand-in editor that Claude Code's Ctrl+G launches when Settings
// sends the prompt to an Editor pane. Written to disk at startup and run via the
// app's own Electron binary in Node mode (ELECTRON_RUN_AS_NODE=1), so it needs no
// node/curl/python on PATH — the same bargain as reporter.cjs.
//
// It edits nothing. It hands the file to the app and then *blocks*, which is the
// entire trick: Claude runs a non-GUI $VISUAL with spawnSync + stdio inherit and
// re-reads the file once the process exits, so "still running" is how we say "the
// user is still typing". The app holds the HTTP response open for exactly that
// long, and its end is the only thing that lets this exit.
//
// Nothing here can wedge a session: the response ending, the socket dropping (app
// gone), a refused connection (app never there) and any signal all end in exit(0),
// and exiting with the file untouched is just Ctrl+G with nothing typed.
//
// Written with no template literals / ${} so it can live inside this TS string.

export const PROMPT_EDITOR_SOURCE = `'use strict'
const http = require('http')

// Port and token come from the environment, not argv. $VISUAL has to survive
// Claude's naive split on spaces (see promptEditorCommand in prompt-edit.ts), so every
// token we don't have to write into it is one less that could carry a space.
// They are already in a Claude session's environment (session-launcher.ts) and
// are inherited straight through Claude into us.
const port = process.env.TERMINATOR_PORT
const token = process.env.TERMINATOR_TOKEN
const sessionId = process.env.TERMINATOR_SESSION_ID || ''
// '--cancel' is the WSL shim saying Ctrl+C was pressed in the pane (see
// wslShimSource): end this session's edit rather than start one.
const cancel = process.argv[2] === '--cancel'
const file = cancel ? '' : process.argv[2]

function done() {
  process.exit(0)
}
process.on('SIGINT', done)
process.on('SIGTERM', done)
process.on('SIGHUP', done)

// CRLF, not LF. Claude has just switched to the alternate screen and the tty is in
// raw mode, where a bare newline moves down without returning the carriage — the
// message would staircase off the right edge.
function say(line) {
  process.stdout.write(line + '\\r\\n')
}

if (!port || !token || (!file && !cancel)) {
  process.stderr.write('Terminator: nothing to edit here.\\r\\n')
  done()
}

// Claude is on the alternate screen waiting for us, so this is the whole of what
// the pane shows for as long as the editing happens in the app.
if (!cancel) {
  say('')
  say('  Editing this in Terminator.')
  say('  Hand it back from the app when you are done, or press Ctrl+C to leave it as it was.')
}

const data = Buffer.from(JSON.stringify({ file: file, sessionId: sessionId }))
const req = http.request(
  {
    host: '127.0.0.1',
    port: Number(port),
    path: cancel ? '/edit-cancel' : '/edit',
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'content-length': data.length,
      authorization: 'Bearer ' + token,
    },
  },
  function (res) {
    // Deliberately no timeout on this one, unlike the reporter: an edit takes as
    // long as it takes. The body is never read — the response *ending* is the
    // signal, and so is the socket dying under us.
    res.resume()
    res.on('end', done)
    res.on('close', done)
  },
)
req.on('error', done)
req.end(data)
`

/**
 * The POSIX shim $VISUAL actually points at.
 *
 * Claude parses $VISUAL as \`cmd.split(" ")\` — no quoting, no escaping — so every
 * token in it must be space-free, and two of the paths we need are not ours to
 * choose: \`process.execPath\` is \`/Applications/Some App.app/...\` if someone renamed
 * the bundle, and userData is \`~/Library/Application Support/Terminator\` on macOS
 * as shipped. A one-token command that is itself a script sidesteps all of it: the
 * paths live *inside* the file, properly quoted, where no splitting happens.
 *
 * Used on macOS and Linux always — not only when the direct form would have
 * failed — so there is one path through this and it is the one that gets exercised.
 * Windows can't: a .cmd shim is not spawnable without a shell, so there the two
 * paths go into $VISUAL directly and a space in either one rules the feature out.
 */
export function posixShimSource(exe: string, script: string): string {
  const q = (s: string): string => `'${s.replace(/'/g, `'\\''`)}'`
  return `#!/bin/sh\n# Generated by Terminator. Runs the in-app prompt editor for Claude's Ctrl+G.\nexec ${q(exe)} ${q(script)} "$@"\n`
}

/**
 * The shim a WSL session's $VISUAL points at, written inside the distro.
 *
 * Same job as `posixShimSource`, with the helper still running on the *Windows*
 * side — through interop — because that side is the one that can reach the app's
 * 127.0.0.1 port. So: the executable by its Linux path (Linux has to find it), the
 * helper by its Windows one (interop passes arguments through untranslated), and
 * `WSLENV` naming what has to cross over with it — Node mode, and the port, token
 * and session id the helper reads from its environment. The file it is handed is a
 * Linux path; the app maps it back through the session's distro (prompt-edit.ts).
 *
 * Ctrl+C needs more. Claude leaves the terminal in cooked mode for its editor, where
 * Ctrl+C is a SIGINT to the whole foreground group: it takes Claude down with it,
 * while the helper — a Windows process — never hears of it. It can't hear the key
 * either: interop gives a GUI-subsystem program like this one no terminal input at
 * all. So the shim listens instead. With signals off and the terminal raw, it runs
 * the helper in the background and reads keys itself; Ctrl+C runs the helper once
 * more with `--cancel`, which asks the app to end the edit, and the first helper
 * exits on that like it would from the tab. The prompt comes back as it was, Claude
 * still running — what Ctrl+C does on Windows. The terminal is restored however
 * this exits. Keys are read with dd rather than a shell's own read, because bash's
 * single-key read turns signals back on — the one thing this must not do.
 */
export function wslShimSource(linuxExe: string, winHelper: string): string {
  const q = (s: string): string => `'${s.replace(/'/g, `'\\''`)}'`
  return [
    '#!/bin/sh',
    "# Generated by Terminator. Runs the in-app prompt editor for Claude's Ctrl+G, on the",
    '# Windows side through WSL interop. Rewritten each time the app starts.',
    'ELECTRON_RUN_AS_NODE=1',
    'WSLENV="ELECTRON_RUN_AS_NODE:TERMINATOR_PORT:TERMINATOR_TOKEN:TERMINATOR_SESSION_ID${WSLENV:+:$WSLENV}"',
    'export ELECTRON_RUN_AS_NODE WSLENV',
    `exe=${q(linuxExe)}`,
    `helper=${q(winHelper)}`,
    'saved=$(stty -g 2>/dev/null) || saved=',
    'if [ -z "$saved" ]; then exec "$exe" "$helper" "$@"; fi',
    `trap 'stty "$saved" 2>/dev/null' EXIT`,
    // Raw, no signals, and a read that gives up after 0.2 s (min 0 time 2), so the
    // loop below can notice the helper finishing without a key being pressed.
    'stty -isig -icanon -echo min 0 time 2 2>/dev/null',
    '"$exe" "$helper" "$@" &',
    'pid=$!',
    'while kill -0 "$pid" 2>/dev/null; do',
    '  case "$(dd bs=1 count=1 2>/dev/null | od -An -tx1)" in *03*) "$exe" "$helper" --cancel ;; esac',
    'done',
    'wait "$pid"',
    '',
  ].join('\n')
}
